export default {
  id: 0,
  name: '',
  producer: '',
  material_type: '',
  production_place: '',
  temporality: '',
  budget: '',
  fitting_date: '',
  recording_date: '',
  created_at: '',
  public_name: '',
  competition: '',
  agency_budget: '',
  use_of_image: '',
  callback_date: '',
  start_date: '',
  end_date: '',
  updated_at: '',
  is_active: false,
  characteristics: '',
  description: ''
}
